-- Campus Trade Platform schema for PostgreSQL 14+.
-- `user` and `order` are SQL keywords, so their identifiers must stay quoted.

CREATE TABLE IF NOT EXISTS "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone VARCHAR(20) NOT NULL UNIQUE,
    student_id VARCHAR(32) NOT NULL UNIQUE,
    real_name VARCHAR(64),
    nickname VARCHAR(64) NOT NULL,
    avatar VARCHAR(512),
    password VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER' CHECK (role IN ('USER', 'ADMIN')),
    status SMALLINT NOT NULL DEFAULT 1 CHECK (status IN (0, 1)),
    deleted SMALLINT NOT NULL DEFAULT 0 CHECK (deleted IN (0, 1)),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE "user" IS '平台用户';
COMMENT ON COLUMN "user".student_id IS '校园学号，格式由应用层校验';
COMMENT ON COLUMN "user".password IS 'BCrypt 密码摘要';

CREATE TABLE IF NOT EXISTS user_auth (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    auth_type VARCHAR(32) NOT NULL DEFAULT 'STUDENT',
    auth_status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
        CHECK (auth_status IN ('PENDING', 'APPROVED', 'REJECTED')),
    auth_time TIMESTAMP,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, auth_type)
);
COMMENT ON TABLE user_auth IS '用户校园身份认证记录';

CREATE TABLE IF NOT EXISTS user_address (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    contact_name VARCHAR(64) NOT NULL,
    contact_phone VARCHAR(20) NOT NULL,
    campus VARCHAR(100) NOT NULL,
    building VARCHAR(100) NOT NULL,
    room VARCHAR(50),
    is_default SMALLINT NOT NULL DEFAULT 0 CHECK (is_default IN (0, 1)),
    deleted SMALLINT NOT NULL DEFAULT 0 CHECK (deleted IN (0, 1)),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_user_address_user_id ON user_address(user_id);
COMMENT ON TABLE user_address IS '用户校内自提地址';

CREATE TABLE IF NOT EXISTS category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    parent_id BIGINT REFERENCES category(id) ON DELETE RESTRICT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    icon VARCHAR(512),
    status SMALLINT NOT NULL DEFAULT 1 CHECK (status IN (0, 1)),
    deleted SMALLINT NOT NULL DEFAULT 0 CHECK (deleted IN (0, 1)),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (parent_id, name)
);
CREATE INDEX IF NOT EXISTS idx_category_parent_id ON category(parent_id);
COMMENT ON TABLE category IS '商品分类树';

CREATE TABLE IF NOT EXISTS product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT,
    category_id BIGINT NOT NULL REFERENCES category(id) ON DELETE RESTRICT,
    title VARCHAR(120) NOT NULL,
    description TEXT NOT NULL,
    price NUMERIC(12, 2) NOT NULL CHECK (price >= 0),
    original_price NUMERIC(12, 2) CHECK (original_price IS NULL OR original_price >= 0),
    condition VARCHAR(20) NOT NULL CHECK (condition IN ('NEW', 'LIKE_NEW', 'GOOD', 'FAIR')),
    trade_type VARCHAR(20) NOT NULL DEFAULT 'SALE' CHECK (trade_type IN ('SALE', 'EXCHANGE')),
    status VARCHAR(24) NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'ON_SALE', 'OFF_SHELF', 'SOLD', 'REJECTED')),
    view_count BIGINT NOT NULL DEFAULT 0 CHECK (view_count >= 0),
    deleted SMALLINT NOT NULL DEFAULT 0 CHECK (deleted IN (0, 1)),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_product_user_id ON product(user_id);
CREATE INDEX IF NOT EXISTS idx_product_category_status ON product(category_id, status);
CREATE INDEX IF NOT EXISTS idx_product_create_time ON product(create_time DESC);
COMMENT ON TABLE product IS '闲置商品';

CREATE TABLE IF NOT EXISTS product_image (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    image_url VARCHAR(512) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_main SMALLINT NOT NULL DEFAULT 0 CHECK (is_main IN (0, 1)),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_product_image_product_id ON product_image(product_id, sort_order);
COMMENT ON TABLE product_image IS '商品图片';

CREATE TABLE IF NOT EXISTS favorite (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, product_id)
);
CREATE INDEX IF NOT EXISTS idx_favorite_product_id ON favorite(product_id);
COMMENT ON TABLE favorite IS '商品收藏关系';

CREATE TABLE IF NOT EXISTS "order" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(40) NOT NULL UNIQUE,
    buyer_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT,
    seller_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT,
    product_id BIGINT NOT NULL REFERENCES product(id) ON DELETE RESTRICT,
    status VARCHAR(24) NOT NULL DEFAULT 'PENDING_CONTACT'
        CHECK (status IN ('PENDING_CONTACT', 'PENDING_PICKUP', 'COMPLETED', 'CANCELLED')),
    cancel_reason VARCHAR(500),
    cancel_by BIGINT REFERENCES "user"(id) ON DELETE RESTRICT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (buyer_id <> seller_id)
);
CREATE INDEX IF NOT EXISTS idx_order_buyer_id ON "order"(buyer_id, create_time DESC);
CREATE INDEX IF NOT EXISTS idx_order_seller_id ON "order"(seller_id, create_time DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uk_order_active_buyer_product
    ON "order"(buyer_id, product_id) WHERE status <> 'CANCELLED';
COMMENT ON TABLE "order" IS '交易订单';

CREATE TABLE IF NOT EXISTS conversation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    buyer_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    seller_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    last_message VARCHAR(1000),
    last_message_time TIMESTAMP,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (product_id, buyer_id, seller_id),
    CHECK (buyer_id <> seller_id)
);
CREATE INDEX IF NOT EXISTS idx_conversation_buyer_time ON conversation(buyer_id, last_message_time DESC);
CREATE INDEX IF NOT EXISTS idx_conversation_seller_time ON conversation(seller_id, last_message_time DESC);
COMMENT ON TABLE conversation IS '买卖双方围绕商品建立的私信会话';

CREATE TABLE IF NOT EXISTS message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES conversation(id) ON DELETE CASCADE,
    sender_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    content VARCHAR(2000) NOT NULL,
    is_read SMALLINT NOT NULL DEFAULT 0 CHECK (is_read IN (0, 1)),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_message_conversation_time ON message(conversation_id, create_time);
CREATE INDEX IF NOT EXISTS idx_message_unread ON message(conversation_id, is_read) WHERE is_read = 0;
COMMENT ON TABLE message IS '私信消息';

CREATE TABLE IF NOT EXISTS wanted_post (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    category_id BIGINT REFERENCES category(id) ON DELETE SET NULL,
    title VARCHAR(120) NOT NULL,
    description TEXT NOT NULL,
    budget NUMERIC(12, 2) CHECK (budget IS NULL OR budget >= 0),
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'CLOSED')),
    deleted SMALLINT NOT NULL DEFAULT 0 CHECK (deleted IN (0, 1)),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_wanted_post_status_time ON wanted_post(status, create_time DESC);
COMMENT ON TABLE wanted_post IS '预留的求购信息（MVP 暂不启用）';

CREATE TABLE IF NOT EXISTS blacklist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES "user"(id) ON DELETE CASCADE,
    reason VARCHAR(500) NOT NULL,
    operator_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE blacklist IS '用户黑名单';

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES product(id) ON DELETE RESTRICT,
    operator_id BIGINT NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT,
    action VARCHAR(20) NOT NULL CHECK (action IN ('APPROVE', 'REJECT')),
    reason VARCHAR(500),
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_audit_log_product_time ON audit_log(product_id, create_time DESC);
COMMENT ON TABLE audit_log IS '商品审核流水';
